import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { UploaderCard } from '../components/UploaderCard';
import { UploadSuccessfully } from '../components/UploadSuccessfully';
// import { UploadProgress } from '../components/UploadProgress';

const Home: NextPage = () => {
  const [imageUrl, setImageUrl] = useState('')
  const [isUploaded, setIsUploaded] = useState(false)
  // const [uploadPercentage, setUploadPercentage] = useState(0)
  
  return (
    <div className='px-5'>
      <Head>
        <title>Image Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center justify-center h-screen'>
        <div className='bg-white dark:bg-slate-800  flex flex-col items-center justify-around rounded-2xl drop-shadow-md'>
          {
            isUploaded?
            <UploadSuccessfully imageUrl={imageUrl} />:
            <UploaderCard setIsUploaded={setIsUploaded} setImageUrl={setImageUrl}/>
          }
        </div>
      </main>

      <footer className='flex py-5 border-t-2 border-gray-300 border-opacity-20 items-center justify-center'>
        <p>created by <a href='https://github.com/JuanDls01' className='font-semibold text-yellow-600 hover:underline'>Juan De los Santos</a> - devChallenges.io</p>
      </footer>
    </div>
  )
}

export default Home
