import type { NextPage } from 'next'
import Head from 'next/head'
import { UploaderCard } from '../components/UploaderCard'

const Home: NextPage = () => {
  return (
    <div className='px-5'>
      <Head>
        <title>Image Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center justify-center h-screen'>
        <UploaderCard />
      </main>

      <footer className='flex py-5 border-t-2 border-gray-300 border-opacity-20 items-center justify-center'>
        <p>created by Juan De los Santos - devChallenges.io</p>
      </footer>
    </div>
  )
}

export default Home
